language: ruby
rvm:
  - 2.3.1
addons:
  hosts:
    - postgres
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  app: chatbot-faq-manager
  api_key:
    secure: "oLaAQHJDS9dhMHNCd1TMLhJdDLRo4p4nHqjL0zRWtrayTuKa+HOB9pLOhVfqTi6cdBXPUquIIQYgqsrhW9BzDrWQ0zITQHx7Q9nVTQH0JNx2X0j90Jy2CKnli7YjfvU9WtnVN3m+86JtGZyFkH6HoNzbMlxtI8zzGAzMT+Vt0E2OmwhOfUuwXjDHTB6u083SgJLWnaiW0r6pcwMNtl8Sj5QUJKJk/jjwtCKbLleiIkkOmJgdAzj88tzmYYgEklXl6lWU8cPEnpUHc5E8FILn81Bv93/+EmwvTH9bsYJXE51KzqYG79L3OiEIFagHQckcoFgDs7zqy7LOCeGBGHE/PnrTljUOGmhjMngduN8TLLbc11FLQv3METfLo0b7VBbSuHHQet5j2MnHH6IO2MTmLQ59N/d1ROgGF+TrUrUq378AUsBbHSRwr607+gllKnLj96ujOH2uvKp50t1z6ZDbc2G/Yvb2PlM88ZVKWi5cRxFglMPxOAfFCkWAJUQOGrPfz/Hq62rwSgyxMcvrfVdOvKBR+TkpiWlQI2AWxJbrnkQDNqYxsoZDO3WP8tXEptYxTyq+5Ciq/uDkSnwIjmVv/hDbBtvrLUggMBgaO5GdT6/L1yM1GEQ7Kh/0u7SoGWtjIJfazGEAtlXWNrrhqfvlhtV04P/AdKkQzWscbf6aUic="
